@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 05 18:40:37 -0600 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim clock_divider_TB_behav -key {Behavioral:sim_1:Functional:clock_divider_TB} -tclbatch clock_divider_TB.tcl -view C:/Verilog/05_06/sequential_ch/clock_divider_TB_behav.wcfg -log simulate.log"
call xsim  clock_divider_TB_behav -key {Behavioral:sim_1:Functional:clock_divider_TB} -tclbatch clock_divider_TB.tcl -view C:/Verilog/05_06/sequential_ch/clock_divider_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
